# Generated by Django 5.0.6 on 2024-06-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writer',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
    ]
